server:
  tomcat:
    threads:
      max: ${TOMCAT_THREADS_MAX:200}

spring:
  config:
    activate:
      on-profile: prod
    import:
      - optional:file:.env[.properties]

  jackson:
    time-zone: Asia/Seoul

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      ssl:
        enabled: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE:10}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        order_inserts: true
        format_sql: false
        jdbc:
          batch_size: 500

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

cors:
  allowed-origins: https://www.raillo.store
  allowed-methods: GET, POST, PUT, DELETE
  allowed-headers: Access-Control-Allow-Origin, Content-type, Access-Control-Allow-Headers, Authorization, X-Requested-With

jwt:
  secret: ${JWT_KEY}

cookie:
  domain: .raillo.store

payment:
  toss:
    api:
      base-url: https://api.tosspayments.com
      client-key: ${TOSS_CLIENT_KEY}
      secret-key: ${TOSS_SECRET_KEY}
      version: v1

# Prometheus
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, metrics
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    tags:
      application: raillo-backend
  endpoint:
    prometheus:
      access: unrestricted

# redis TTL
redis:
  ttl:
    pending-booking: 10m
    pending-booking-member-key: 580s # 유령 인덱스 방지를 위해 주 키의 TTL 설정 값보다 20초 짧게 설정
